 <isomsg>
     <field id="0" value="0200" />
     <field id="2" value="4731890102563782" />
     <field id="3" value="180000" />
     <field id="4" value="000000000000" />
     <field id="11" value="000770" />
     <field id="12" value="091713" />
     <field id="13" value="0106" />
     <field id="14" value="1001" />
     <field id="15" value="0106" />
     <field id="18" value="6011" />
     <field id="22" value="021" />
     <field id="24" value="441" />
     <field id="35" value="4731890102563782=1010126765000000" />
     <field id="37" value="000000000014" />
     <field id="41" value="00005500" />
     <field id="42" value="1001" />
     <field id="49" value="360" />
     <field id="49" value="360"/>
    </isomsg>
